// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(
		server.WithHostPorts(":8080"),
	)

	h.LoadHTMLGlob("html/packet/*")

	h.StaticFile("favicon.ico", "./html/packet/favicon.ico")

	register(h)
	h.Spin()
}
