// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"packet_cloud/biz/handler/packet"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	// your code ...
	r.GET("/v1/packet/edit", packet.OnlineEdit)
}
