// Code generated by hertz generator.

package Packet

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createpacketresponseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querypacketresponseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _packetMw() []app.HandlerFunc {
	// your code...
	return nil
}
