// Code generated by hertztool.

package handler

import (
	"context"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"log"
	"packet_cloud/service/readwriter"

	"github.com/cloudwego/hertz/pkg/app"
	packet "packet_cloud/biz/model/hertz/packet"
)

// ListPacket .
// @router /v1/packet/list [GET]
func ListPacket(ctx context.Context, c *app.RequestContext) {
	var err error
	var req packet.ListPacketReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	packets, err := readwriter.ReadPacket(readwriter.LFS)
	if err != nil {
		log.Printf("[ListPacket] username=%s, time=%s, error=%s\n", req.Username, req.Time, err)
		c.JSON(consts.StatusInternalServerError, err)
		return
	}

	// 数据太多，行数据改为接口获取
	for i := 0; i < len(packets); i++ {
		packets[i].UserPackets = make([]*packet.UserPacket, 0)
	}

	c.JSON(consts.StatusOK, &packet.ListPacketResp{
		Code:         0,
		Msg:          "获取云数据包成功",
		CloudPackets: packets,
	})
}
